/*
 * Principal.java
 *
 * Created on 24 de septiembre de 2006, 10:35
 */

package ArchivoHash.gui;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;

/** La clase <code>Principal</code> contiene la ventana donde se seleccionan
 * las opciones y se muestran las estadisticas generadas
 */
public class Principal extends javax.swing.JFrame {

    private File archivo;

    /** Crea una nueva ventana Principal */
    public Principal() {
	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        nuevaEstadistica = new javax.swing.JMenuItem();
        cargarEstadistica = new javax.swing.JMenuItem();
        limpiar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(640, 480));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        menu.setText("Estadisticas");

        nuevaEstadistica.setText("Nueva estadistica");
        nuevaEstadistica.setPreferredSize(new java.awt.Dimension(55, 19));
        nuevaEstadistica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nuevaEstadisticaActionPerformed(evt);
            }
        });
        menu.add(nuevaEstadistica);

        cargarEstadistica.setText("Cargar estadistica");
        cargarEstadistica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cargarEstadisticaActionPerformed(evt);
            }
        });
        menu.add(cargarEstadistica);

        limpiar.setText("Limpiar Estadisticas");
        limpiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limpiarActionPerformed(evt);
            }
        });
        menu.add(limpiar);

        jMenuBar2.add(menu);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Este metodo carga un informe estadistico guardado en el disco*/
    private void cargarEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarEstadisticaActionPerformed
	JFileChooser aa = new JFileChooser();
	UIMostrarEstadistica panel;

	int returnVal = aa.showOpenDialog(null);

	//Si se selecciona un archivo
	if (returnVal == JFileChooser.APPROVE_OPTION) {
	    archivo = aa.getSelectedFile();
	    try {
		//Carga el informe estadistico
		ObjectInputStream in = new ObjectInputStream(new FileInputStream(archivo));
		panel = (UIMostrarEstadistica) (in.readObject());
		jTabbedPane1.addTab("Estadistica", panel);
	    } catch (ClassNotFoundException CNFE) {
		JOptionPane.showMessageDialog(this, new String("Error en la carga"));
	    } catch (IOException IOE) {
		JOptionPane.showMessageDialog(this, new String("Error en la carga"));
	    }
	}
    }//GEN-LAST:event_cargarEstadisticaActionPerformed

    /** Limpia todos los informes estad�sticos*/
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
	jTabbedPane1.removeAll();
    }//GEN-LAST:event_limpiarActionPerformed

    /** Abre una ventana para generar un nuevo informe estadistico*/
    private void nuevaEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaEstadisticaActionPerformed
	new UICalcularEstadistica(this).setVisible(true);
    }//GEN-LAST:event_nuevaEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		new Principal().setVisible(true);
	    }
	});
    }

    /** Añade una nueva pestana con un informe
     * @param ui 
     */
    public void addPestana(UIMostrarEstadistica ui) {
	jTabbedPane1.addTab("Estadistica", ui);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cargarEstadistica;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem limpiar;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem nuevaEstadistica;
    // End of variables declaration//GEN-END:variables
}